package com.thatsdarlingmama.security;

import java.security.Provider;

public class QuantumProvider extends Provider {
    public QuantumProvider() {
        super("Quantum", "1.0", "Provides all current Quantum Encryption Algorithms");
        put("Signature.Dilithium2", "com.thatsdarlingmama.security.signature.Dilithium2SignatureSpi");
        put("Signature.Dilithium3", "com.thatsdarlingmama.security.signature.Dilithium3SignatureSpi");
        put("Signature.Dilithium5", "com.thatsdarlingmama.security.signature.Dilithium5SignatureSpi");
        put("Signature.Dilithium2-AES", "com.thatsdarlingmama.security.signature.Dilithium2AESSignatureSpi");
        put("Signature.Dilithium3-AES", "com.thatsdarlingmama.security.signature.Dilithium3AESSignatureSpi");
        put("Signature.Dilithium5-AES", "com.thatsdarlingmama.security.signature.Dilithium5AESSignatureSpi");
        put("Signature.Falcon-512", "com.thatsdarlingmama.security.signature.Falcon512SignatureSpi");
        put("Signature.Falcon-1024", "com.thatsdarlingmama.security.signature.Falcon1024SignatureSpi");
        put("Signature.Rainbow-I-Classic", "com.thatsdarlingmama.security.signature.RainbowIClassicSignatureSpi");
        put("Signature.Rainbow-I-Circumzenithal", "com.thatsdarlingmama.security.signature.RainbowICircumzenithalSignatureSpi");
        put("Signature.Rainbow-I-Compressed", "com.thatsdarlingmama.security.signature.RainbowICompressedSignatureSpi");
        put("Signature.Rainbow-III-Classic", "com.thatsdarlingmama.security.signature.RainbowIIIClassicSignatureSpi");
        put("Signature.Rainbow-III-Circumzenithal", "com.thatsdarlingmama.security.signature.RainbowIIICircumzenithalSignatureSpi");
        put("Signature.Rainbow-III-Compressed", "com.thatsdarlingmama.security.signature.RainbowIIICompressedSignatureSpi");
        put("Signature.Rainbow-V-Classic", "com.thatsdarlingmama.security.signature.RainbowVClassicSignatureSpi");
        put("Signature.Rainbow-V-Circumzenithal", "com.thatsdarlingmama.security.signature.RainbowVCircumzenithalSignatureSpi");
        put("Signature.Rainbow-V-Compressed", "com.thatsdarlingmama.security.signature.RainbowVCompressedSignatureSpi");
        put("Signature.SPHINCS+-Haraka-128f-robust", "com.thatsdarlingmama.security.signature.SPHINCSPlusHaraka128frobustSignatureSpi");
        put("Signature.SPHINCS+-Haraka-128f-simple", "com.thatsdarlingmama.security.signature.SPHINCSPlusHaraka128fsimpleSignatureSpi");
        put("Signature.SPHINCS+-Haraka-128s-robust", "com.thatsdarlingmama.security.signature.SPHINCSPlusHaraka128srobustSignatureSpi");
        put("Signature.SPHINCS+-Haraka-128s-simple", "com.thatsdarlingmama.security.signature.SPHINCSPlusHaraka128ssimpleSignatureSpi");
        put("Signature.SPHINCS+-Haraka-192f-robust", "com.thatsdarlingmama.security.signature.SPHINCSPlusHaraka192frobustSignatureSpi");
        put("Signature.SPHINCS+-Haraka-192f-simple", "com.thatsdarlingmama.security.signature.SPHINCSPlusHaraka192fsimpleSignatureSpi");
        put("Signature.SPHINCS+-Haraka-192s-robust", "com.thatsdarlingmama.security.signature.SPHINCSPlusHaraka192srobustSignatureSpi");
        put("Signature.SPHINCS+-Haraka-192s-simple", "com.thatsdarlingmama.security.signature.SPHINCSPlusHaraka192ssimpleSignatureSpi");
        put("Signature.SPHINCS+-Haraka-256f-robust", "com.thatsdarlingmama.security.signature.SPHINCSPlusHaraka256frobustSignatureSpi");
        put("Signature.SPHINCS+-Haraka-256f-simple", "com.thatsdarlingmama.security.signature.SPHINCSPlusHaraka256fsimpleSignatureSpi");
        put("Signature.SPHINCS+-Haraka-256s-robust", "com.thatsdarlingmama.security.signature.SPHINCSPlusHaraka256srobustSignatureSpi");
        put("Signature.SPHINCS+-Haraka-256s-simple", "com.thatsdarlingmama.security.signature.SPHINCSPlusHaraka256ssimpleSignatureSpi");
        put("Signature.SPHINCS+-SHA256-128f-robust", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHA256128frobustSignatureSpi");
        put("Signature.SPHINCS+-SHA256-128f-simple", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHA256128fsimpleSignatureSpi");
        put("Signature.SPHINCS+-SHA256-128s-robust", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHA256128srobustSignatureSpi");
        put("Signature.SPHINCS+-SHA256-128s-simple", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHA256128ssimpleSignatureSpi");
        put("Signature.SPHINCS+-SHA256-192f-robust", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHA256192frobustSignatureSpi");
        put("Signature.SPHINCS+-SHA256-192f-simple", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHA256192fsimpleSignatureSpi");
        put("Signature.SPHINCS+-SHA256-192s-robust", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHA256192srobustSignatureSpi");
        put("Signature.SPHINCS+-SHA256-192s-simple", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHA256192ssimpleSignatureSpi");
        put("Signature.SPHINCS+-SHA256-256f-robust", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHA256256frobustSignatureSpi");
        put("Signature.SPHINCS+-SHA256-256f-simple", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHA256256fsimpleSignatureSpi");
        put("Signature.SPHINCS+-SHA256-256s-robust", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHA256256srobustSignatureSpi");
        put("Signature.SPHINCS+-SHA256-256s-simple", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHA256256ssimpleSignatureSpi");
        put("Signature.SPHINCS+-SHAKE256-128f-robust", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHAKE256128frobustSignatureSpi");
        put("Signature.SPHINCS+-SHAKE256-128f-simple", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHAKE256128fsimpleSignatureSpi");
        put("Signature.SPHINCS+-SHAKE256-128s-robust", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHAKE256128srobustSignatureSpi");
        put("Signature.SPHINCS+-SHAKE256-128s-simple", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHAKE256128ssimpleSignatureSpi");
        put("Signature.SPHINCS+-SHAKE256-192f-robust", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHAKE256192frobustSignatureSpi");
        put("Signature.SPHINCS+-SHAKE256-192f-simple", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHAKE256192fsimpleSignatureSpi");
        put("Signature.SPHINCS+-SHAKE256-192s-robust", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHAKE256192srobustSignatureSpi");
        put("Signature.SPHINCS+-SHAKE256-192s-simple", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHAKE256192ssimpleSignatureSpi");
        put("Signature.SPHINCS+-SHAKE256-256f-robust", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHAKE256256frobustSignatureSpi");
        put("Signature.SPHINCS+-SHAKE256-256f-simple", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHAKE256256fsimpleSignatureSpi");
        put("Signature.SPHINCS+-SHAKE256-256s-robust", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHAKE256256srobustSignatureSpi");
        put("Signature.SPHINCS+-SHAKE256-256s-simple", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHAKE256256ssimpleSignatureSpi");
        put("Signature.picnic_L1_FS", "com.thatsdarlingmama.security.signature.picnicL1FSSignatureSpi");
        put("Signature.picnic_L1_UR", "com.thatsdarlingmama.security.signature.picnicL1URSignatureSpi");
        put("Signature.picnic_L1_full", "com.thatsdarlingmama.security.signature.picnicL1fullSignatureSpi");
        put("Signature.picnic_L3_FS", "com.thatsdarlingmama.security.signature.picnicL3FSSignatureSpi");
        put("Signature.picnic_L3_UR", "com.thatsdarlingmama.security.signature.picnicL3URSignatureSpi");
        put("Signature.picnic_L3_full", "com.thatsdarlingmama.security.signature.picnicL3fullSignatureSpi");
        put("Signature.picnic_L5_FS", "com.thatsdarlingmama.security.signature.picnicL5FSSignatureSpi");
        put("Signature.picnic_L5_UR", "com.thatsdarlingmama.security.signature.picnicL5URSignatureSpi");
        put("Signature.picnic_L5_full", "com.thatsdarlingmama.security.signature.picnicL5fullSignatureSpi");
        put("Signature.picnic3_L1", "com.thatsdarlingmama.security.signature.picnic3L1SignatureSpi");
        put("Signature.picnic3_L3", "com.thatsdarlingmama.security.signature.picnic3L3SignatureSpi");
        put("Signature.picnic3_L5", "com.thatsdarlingmama.security.signature.picnic3L3SignatureSpi");

        put("KeyAgreement.LightSaber-KEM", "com.thatsdarlingmama.security.keyagreement.LightSaberKEMKeyAgreementSpi");
        put("KeyAgreement.BIKE-L1", "com.thatsdarlingmama.security.keyagreement.BIKEL1KeyAgreementSpi");
        put("KeyAgreement.BIKE-L3", "com.thatsdarlingmama.security.keyagreement.BIKEL3KeyAgreementSpi");
        put("KeyAgreement.Classic-McEliece-348864", "com.thatsdarlingmama.security.keyagreement.ClassicMcEliece348864KeyAgreementSpi");
        put("KeyAgreement.Classic-McEliece-348864f", "com.thatsdarlingmama.security.keyagreement.ClassicMcEliece348864fKeyAgreementSpi");
        put("KeyAgreement.Classic-McEliece-460896", "com.thatsdarlingmama.security.keyagreement.ClassicMcEliece460896KeyAgreementSpi");
        put("KeyAgreement.Classic-McEliece-460896f", "com.thatsdarlingmama.security.keyagreement.ClassicMcEliece460896fKeyAgreementSpi");
        put("KeyAgreement.Classic-McEliece-6688128", "com.thatsdarlingmama.security.keyagreement.ClassicMcEliece6688128KeyAgreementSpi");
        put("KeyAgreement.Classic-McEliece-6688128f", "com.thatsdarlingmama.security.keyagreement.ClassicMcEliece6688128fKeyAgreementSpi");
        put("KeyAgreement.Classic-McEliece-6960119", "com.thatsdarlingmama.security.keyagreement.ClassicMcEliece6960119KeyAgreementSpi");
        put("KeyAgreement.Classic-McEliece-6960119f", "com.thatsdarlingmama.security.keyagreement.ClassicMcEliece6960119fKeyAgreementSpi");
        put("KeyAgreement.Classic-McEliece-8192128", "com.thatsdarlingmama.security.keyagreement.ClassicMcEliece8192128KeyAgreementSpi");
        put("KeyAgreement.Classic-McEliece-8192128f", "com.thatsdarlingmama.security.keyagreement.ClassicMcEliece8192128fKeyAgreementSpi");
        put("KeyAgreement.HQC-128", "com.thatsdarlingmama.security.keyagreement.HQC128KeyAgreementSpi");
        put("KeyAgreement.HQC-192", "com.thatsdarlingmama.security.keyagreement.HQC192KeyAgreementSpi");
        put("KeyAgreement.HQC-256", "com.thatsdarlingmama.security.keyagreement.HQC256KeyAgreementSpi");
        put("KeyAgreement.Kyber512", "com.thatsdarlingmama.security.keyagreement.Kyber512KeyAgreementSpi");
        put("KeyAgreement.Kyber768", "com.thatsdarlingmama.security.keyagreement.Kyber768KeyAgreementSpi");
        put("KeyAgreement.Kyber1024", "com.thatsdarlingmama.security.keyagreement.Kyber1024KeyAgreementSpi");
        put("KeyAgreement.Kyber512-90s", "com.thatsdarlingmama.security.keyagreement.Kyber51290sKeyAgreementSpi");
        put("KeyAgreement.Kyber768-90s", "com.thatsdarlingmama.security.keyagreement.Kyber76890sKeyAgreementSpi");
        put("KeyAgreement.Kyber1024-90s", "com.thatsdarlingmama.security.keyagreement.Kyber102490sKeyAgreementSpi");
        put("KeyAgreement.NTRU-HPS-2048-509", "com.thatsdarlingmama.security.keyagreement.NTRUHPS2048509KeyAgreementSpi");
        put("KeyAgreement.NTRU-HPS-2048-677", "com.thatsdarlingmama.security.keyagreement.NTRUHPS2048677KeyAgreementSpi");
        put("KeyAgreement.NTRU-HPS-4096-821", "com.thatsdarlingmama.security.keyagreement.NTRUHPS4096821KeyAgreementSpi");
        put("KeyAgreement.NTRU-HPS-4096-1229", "com.thatsdarlingmama.security.keyagreement.NTRUHPS40961229KeyAgreementSpi");
        put("KeyAgreement.NTRU-HRSS-701", "com.thatsdarlingmama.security.keyagreement.NTRUHRSS701KeyAgreementSpi");
        put("KeyAgreement.NTRU-HRSS-1373", "com.thatsdarlingmama.security.keyagreement.NTRUHRSS1373KeyAgreementSpi");
        put("KeyAgreement.ntrulpr653", "com.thatsdarlingmama.security.keyagreement.ntrulpr653KeyAgreementSpi");
        put("KeyAgreement.ntrulpr761", "com.thatsdarlingmama.security.keyagreement.ntrulpr761KeyAgreementSpi");
        put("KeyAgreement.ntrulpr857", "com.thatsdarlingmama.security.keyagreement.ntrulpr857KeyAgreementSpi");
        put("KeyAgreement.ntrulpr1277", "com.thatsdarlingmama.security.keyagreement.ntrulpr1277KeyAgreementSpi");
        put("KeyAgreement.sntrup653", "com.thatsdarlingmama.security.keyagreement.sntrup653KeyAgreementSpi");
        put("KeyAgreement.sntrup761", "com.thatsdarlingmama.security.keyagreement.sntrup761KeyAgreementSpi");
        put("KeyAgreement.sntrup857", "com.thatsdarlingmama.security.keyagreement.sntrup857KeyAgreementSpi");
        put("KeyAgreement.sntrup1277", "com.thatsdarlingmama.security.keyagreement.sntrup1277KeyAgreementSpi");
        put("KeyAgreement.LightSaber-KEM", "com.thatsdarlingmama.security.keyagreement.LightSaberKEMKeyAgreementSpi");
        put("KeyAgreement.Saber-KEM", "com.thatsdarlingmama.security.keyagreement.SaberKEMKeyAgreementSpi");
        put("KeyAgreement.FireSaber-KEM", "com.thatsdarlingmama.security.keyagreement.FireSaberKEMKeyAgreementSpi");
        put("KeyAgreement.FrodoKEM-640-AES", "com.thatsdarlingmama.security.keyagreement.FrodoKEM640AESKeyAgreementSpi");
        put("KeyAgreement.FrodoKEM-640-SHAKE", "com.thatsdarlingmama.security.keyagreement.FrodoKEM640SHAKEKeyAgreementSpi");
        put("KeyAgreement.FrodoKEM-976-AES", "com.thatsdarlingmama.security.keyagreement.FrodoKEM976AESKeyAgreementSpi");
        put("KeyAgreement.FrodoKEM-976-SHAKE", "com.thatsdarlingmama.security.keyagreement.FrodoKEM976SHAKEKeyAgreementSpi");
        put("KeyAgreement.FrodoKEM-1344-AES", "com.thatsdarlingmama.security.keyagreement.FrodoKEM1344AESKeyAgreementSpi");
        put("KeyAgreement.FrodoKEM-1344-SHAKE", "com.thatsdarlingmama.security.keyagreement.FrodoKEM1344SHAKEKeyAgreementSpi");
        put("KeyAgreement.SIDH-p434", "com.thatsdarlingmama.security.keyagreement.SIDHp434KeyAgreementSpi");
        put("KeyAgreement.SIDH-p503", "com.thatsdarlingmama.security.keyagreement.SIDHp503KeyAgreementSpi");
        put("KeyAgreement.SIDH-p610", "com.thatsdarlingmama.security.keyagreement.SIDHp610KeyAgreementSpi");
        put("KeyAgreement.SIDH-p751", "com.thatsdarlingmama.security.keyagreement.SIDHp751KeyAgreementSpi");
        put("KeyAgreement.SIDH-p434-compressed", "com.thatsdarlingmama.security.keyagreement.SIDHp434compressedKeyAgreementSpi");
        put("KeyAgreement.SIDH-p503-compressed", "com.thatsdarlingmama.security.keyagreement.SIDHp503compressedKeyAgreementSpi");
        put("KeyAgreement.SIDH-p610-compressed", "com.thatsdarlingmama.security.keyagreement.SIDHp610compressedKeyAgreementSpi");
        put("KeyAgreement.SIDH-p751-compressed", "com.thatsdarlingmama.security.keyagreement.SIDHp751compressedKeyAgreementSpi");
        put("KeyAgreement.SIKE-p434", "com.thatsdarlingmama.security.keyagreement.SIKEp434KeyAgreementSpi");
        put("KeyAgreement.SIKE-p503", "com.thatsdarlingmama.security.keyagreement.SIKEp503KeyAgreementSpi");
        put("KeyAgreement.SIKE-p610", "com.thatsdarlingmama.security.keyagreement.SIKEp610KeyAgreementSpi");
        put("KeyAgreement.SIKE-p751", "com.thatsdarlingmama.security.keyagreement.SIKEp751KeyAgreementSpi");
        put("KeyAgreement.SIKE-p434-compressed", "com.thatsdarlingmama.security.keyagreement.SIKEp434compressedKeyAgreementSpi");
        put("KeyAgreement.SIKE-p503-compressed", "com.thatsdarlingmama.security.keyagreement.SIKEp503compressedKeyAgreementSpi");
        put("KeyAgreement.SIKE-p610-compressed", "com.thatsdarlingmama.security.keyagreement.SIKEp610compressedKeyAgreementSpi");
        put("KeyAgreement.SIKE-p751-compressed", "com.thatsdarlingmama.security.keyagreement.SIKEp751compressedKeyAgreementSpi");

        put("KeyPairGenerator.BIKE-L1", "com.thatsdarlingmama.security.keypairgenerator.BIKEL1KeyPairGeneratorSpi");
        put("KeyPairGenerator.BIKE-L3", "com.thatsdarlingmama.security.keypairgenerator.BIKEL3KeyPairGeneratorSpi");
        put("KeyPairGenerator.Classic-McEliece-348864", "com.thatsdarlingmama.security.keypairgenerator.ClassicMcEliece348864KeyPairGeneratorSpi");
        put("KeyPairGenerator.Classic-McEliece-348864f", "com.thatsdarlingmama.security.keypairgenerator.ClassicMcEliece348864fKeyPairGeneratorSpi");
        put("KeyPairGenerator.Classic-McEliece-460896", "com.thatsdarlingmama.security.keypairgenerator.ClassicMcEliece460896KeyPairGeneratorSpi");
        put("KeyPairGenerator.Classic-McEliece-460896f", "com.thatsdarlingmama.security.keypairgenerator.ClassicMcEliece460896fKeyPairGeneratorSpi");
        put("KeyPairGenerator.Classic-McEliece-6688128", "com.thatsdarlingmama.security.keypairgenerator.ClassicMcEliece6688128KeyPairGeneratorSpi");
        put("KeyPairGenerator.Classic-McEliece-6688128f", "com.thatsdarlingmama.security.keypairgenerator.ClassicMcEliece6688128fKeyPairGeneratorSpi");
        put("KeyPairGenerator.Classic-McEliece-6960119", "com.thatsdarlingmama.security.keypairgenerator.ClassicMcEliece6960119KeyPairGeneratorSpi");
        put("KeyPairGenerator.Classic-McEliece-6960119f", "com.thatsdarlingmama.security.keypairgenerator.ClassicMcEliece6960119fKeyPairGeneratorSpi");
        put("KeyPairGenerator.Classic-McEliece-8192128", "com.thatsdarlingmama.security.keypairgenerator.ClassicMcEliece8192128KeyPairGeneratorSpi");
        put("KeyPairGenerator.Classic-McEliece-8192128f", "com.thatsdarlingmama.security.keypairgenerator.ClassicMcEliece8192128fKeyPairGeneratorSpi");
        put("KeyPairGenerator.HQC-128", "com.thatsdarlingmama.security.keypairgenerator.HQC128KeyPairGeneratorSpi");
        put("KeyPairGenerator.HQC-192", "com.thatsdarlingmama.security.keypairgenerator.HQC192KeyPairGeneratorSpi");
        put("KeyPairGenerator.HQC-256", "com.thatsdarlingmama.security.keypairgenerator.HQC256KeyPairGeneratorSpi");
        put("KeyPairGenerator.Kyber512", "com.thatsdarlingmama.security.keypairgenerator.Kyber512KeyPairGeneratorSpi");
        put("KeyPairGenerator.Kyber768", "com.thatsdarlingmama.security.keypairgenerator.Kyber768KeyPairGeneratorSpi");
        put("KeyPairGenerator.Kyber1024", "com.thatsdarlingmama.security.keypairgenerator.Kyber1024KeyPairGeneratorSpi");
        put("KeyPairGenerator.Kyber512-90s", "com.thatsdarlingmama.security.keypairgenerator.Kyber51290sKeyPairGeneratorSpi");
        put("KeyPairGenerator.Kyber768-90s", "com.thatsdarlingmama.security.keypairgenerator.Kyber76890sKeyPairGeneratorSpi");
        put("KeyPairGenerator.Kyber1024-90s", "com.thatsdarlingmama.security.keypairgenerator.Kyber102490sKeyPairGeneratorSpi");
        put("KeyPairGenerator.NTRU-HPS-2048-509", "com.thatsdarlingmama.security.keypairgenerator.NTRUHPS2048509KeyPairGeneratorSpi");
        put("KeyPairGenerator.NTRU-HPS-2048-677", "com.thatsdarlingmama.security.keypairgenerator.NTRUHPS2048677KeyPairGeneratorSpi");
        put("KeyPairGenerator.NTRU-HPS-4096-821", "com.thatsdarlingmama.security.keypairgenerator.NTRUHPS4096821KeyPairGeneratorSpi");
        put("KeyPairGenerator.NTRU-HPS-4096-1229", "com.thatsdarlingmama.security.keypairgenerator.NTRUHPS40961229KeyPairGeneratorSpi");
        put("KeyPairGenerator.NTRU-HRSS-701", "com.thatsdarlingmama.security.keypairgenerator.NTRUHRSS701KeyPairGeneratorSpi");
        put("KeyPairGenerator.NTRU-HRSS-1373", "com.thatsdarlingmama.security.keypairgenerator.NTRUHRSS1373KeyPairGeneratorSpi");
        put("KeyPairGenerator.ntrulpr653", "com.thatsdarlingmama.security.keypairgenerator.ntrulpr653KeyPairGeneratorSpi");
        put("KeyPairGenerator.ntrulpr761", "com.thatsdarlingmama.security.keypairgenerator.ntrulpr761KeyPairGeneratorSpi");
        put("KeyPairGenerator.ntrulpr857", "com.thatsdarlingmama.security.keypairgenerator.ntrulpr857KeyPairGeneratorSpi");
        put("KeyPairGenerator.ntrulpr1277", "com.thatsdarlingmama.security.keypairgenerator.ntrulpr1277KeyPairGeneratorSpi");
        put("KeyPairGenerator.sntrup653", "com.thatsdarlingmama.security.keypairgenerator.sntrup653KeyPairGeneratorSpi");
        put("KeyPairGenerator.sntrup761", "com.thatsdarlingmama.security.keypairgenerator.sntrup761KeyPairGeneratorSpi");
        put("KeyPairGenerator.sntrup857", "com.thatsdarlingmama.security.keypairgenerator.sntrup857KeyPairGeneratorSpi");
        put("KeyPairGenerator.sntrup1277", "com.thatsdarlingmama.security.keypairgenerator.sntrup1277KeyPairGeneratorSpi");
        put("KeyPairGenerator.LightSaber-KEM", "com.thatsdarlingmama.security.keypairgenerator.LightSaberKEMKeyPairGeneratorSpi");
        put("KeyPairGenerator.Saber-KEM", "com.thatsdarlingmama.security.keypairgenerator.SaberKEMKeyPairGeneratorSpi");
        put("KeyPairGenerator.FireSaber-KEM", "com.thatsdarlingmama.security.keypairgenerator.FireSaberKEMKeyPairGeneratorSpi");
        put("KeyPairGenerator.FrodoKEM-640-AES", "com.thatsdarlingmama.security.keypairgenerator.FrodoKEM640AESKeyPairGeneratorSpi");
        put("KeyPairGenerator.FrodoKEM-640-SHAKE", "com.thatsdarlingmama.security.keypairgenerator.FrodoKEM640SHAKEKeyPairGeneratorSpi");
        put("KeyPairGenerator.FrodoKEM-976-AES", "com.thatsdarlingmama.security.keypairgenerator.FrodoKEM976AESKeyPairGeneratorSpi");
        put("KeyPairGenerator.FrodoKEM-976-SHAKE", "com.thatsdarlingmama.security.keypairgenerator.FrodoKEM976SHAKEKeyPairGeneratorSpi");
        put("KeyPairGenerator.FrodoKEM-1344-AES", "com.thatsdarlingmama.security.keypairgenerator.FrodoKEM1344AESKeyPairGeneratorSpi");
        put("KeyPairGenerator.FrodoKEM-1344-SHAKE", "com.thatsdarlingmama.security.keypairgenerator.FrodoKEM1344SHAKEKeyPairGeneratorSpi");
        put("KeyPairGenerator.SIDH-p434", "com.thatsdarlingmama.security.keypairgenerator.SIDHp434KeyPairGeneratorSpi");
        put("KeyPairGenerator.SIDH-p503", "com.thatsdarlingmama.security.keypairgenerator.SIDHp503KeyPairGeneratorSpi");
        put("KeyPairGenerator.SIDH-p610", "com.thatsdarlingmama.security.keypairgenerator.SIDHp610KeyPairGeneratorSpi");
        put("KeyPairGenerator.SIDH-p751", "com.thatsdarlingmama.security.keypairgenerator.SIDHp751KeyPairGeneratorSpi");
        put("KeyPairGenerator.SIDH-p434-compressed", "com.thatsdarlingmama.security.keypairgenerator.SIDHp434compressedKeyPairGeneratorSpi");
        put("KeyPairGenerator.SIDH-p503-compressed", "com.thatsdarlingmama.security.keypairgenerator.SIDHp503compressedKeyPairGeneratorSpi");
        put("KeyPairGenerator.SIDH-p610-compressed", "com.thatsdarlingmama.security.keypairgenerator.SIDHp610compressedKeyPairGeneratorSpi");
        put("KeyPairGenerator.SIDH-p751-compressed", "com.thatsdarlingmama.security.keypairgenerator.SIDHp751compressedKeyPairGeneratorSpi");
        put("KeyPairGenerator.SIKE-p434", "com.thatsdarlingmama.security.keypairgenerator.SIKEp434KeyPairGeneratorSpi");
        put("KeyPairGenerator.SIKE-p503", "com.thatsdarlingmama.security.keypairgenerator.SIKEp503KeyPairGeneratorSpi");
        put("KeyPairGenerator.SIKE-p610", "com.thatsdarlingmama.security.keypairgenerator.SIKEp610KeyPairGeneratorSpi");
        put("KeyPairGenerator.SIKE-p751", "com.thatsdarlingmama.security.keypairgenerator.SIKEp751KeyPairGeneratorSpi");
        put("KeyPairGenerator.SIKE-p434-compressed", "com.thatsdarlingmama.security.keypairgenerator.SIKEp434compressedKeyPairGeneratorSpi");
        put("KeyPairGenerator.SIKE-p503-compressed", "com.thatsdarlingmama.security.keypairgenerator.SIKEp503compressedKeyPairGeneratorSpi");
        put("KeyPairGenerator.SIKE-p610-compressed", "com.thatsdarlingmama.security.keypairgenerator.SIKEp610compressedKeyPairGeneratorSpi");
        put("KeyPairGenerator.SIKE-p751-compressed", "com.thatsdarlingmama.security.keypairgenerator.SIKEp751compressedKeyPairGeneratorSpi");
        put("KeyPairGenerator.Dilithium2", "com.thatsdarlingmama.security.keypairgenerator.Dilithium2KeyPairGeneratorSpi");
        put("KeyPairGenerator.Dilithium3", "com.thatsdarlingmama.security.keypairgenerator.Dilithium3KeyPairGeneratorSpi");
        put("KeyPairGenerator.Dilithium5", "com.thatsdarlingmama.security.keypairgenerator.Dilithium5KeyPairGeneratorSpi");
        put("KeyPairGenerator.Dilithium2-AES", "com.thatsdarlingmama.security.keypairgenerator.Dilithium2AESKeyPairGeneratorSpi");
        put("KeyPairGenerator.Dilithium3-AES", "com.thatsdarlingmama.security.keypairgenerator.Dilithium3AESKeyPairGeneratorSpi");
        put("KeyPairGenerator.Dilithium5-AES", "com.thatsdarlingmama.security.keypairgenerator.Dilithium5AESKeyPairGeneratorSpi");
        put("KeyPairGenerator.Falcon-512", "com.thatsdarlingmama.security.keypairgenerator.Falcon512KeyPairGeneratorSpi");
        put("KeyPairGenerator.Falcon-1024", "com.thatsdarlingmama.security.keypairgenerator.Falcon1024KeyPairGeneratorSpi");
        put("KeyPairGenerator.Rainbow-I-Classic", "com.thatsdarlingmama.security.keypairgenerator.RainbowIClassicKeyPairGeneratorSpi");
        put("KeyPairGenerator.Rainbow-I-Circumzenithal", "com.thatsdarlingmama.security.keypairgenerator.RainbowICircumzenithalKeyPairGeneratorSpi");
        put("KeyPairGenerator.Rainbow-I-Compressed", "com.thatsdarlingmama.security.keypairgenerator.RainbowICompressedKeyPairGeneratorSpi");
        put("KeyPairGenerator.Rainbow-III-Classic", "com.thatsdarlingmama.security.keypairgenerator.RainbowIIIClassicKeyPairGeneratorSpi");
        put("KeyPairGenerator.Rainbow-III-Circumzenithal", "com.thatsdarlingmama.security.keypairgenerator.RainbowIIICircumzenithalKeyPairGeneratorSpi");
        put("KeyPairGenerator.Rainbow-III-Compressed", "com.thatsdarlingmama.security.keypairgenerator.RainbowIIICompressedKeyPairGeneratorSpi");
        put("KeyPairGenerator.Rainbow-V-Classic", "com.thatsdarlingmama.security.keypairgenerator.RainbowVClassicKeyPairGeneratorSpi");
        put("KeyPairGenerator.Rainbow-V-Circumzenithal", "com.thatsdarlingmama.security.keypairgenerator.RainbowVCircumzenithalKeyPairGeneratorSpi");
        put("KeyPairGenerator.Rainbow-V-Compressed", "com.thatsdarlingmama.security.keypairgenerator.RainbowVCompressedKeyPairGeneratorSpi");
        put("KeyPairGenerator.SPHINCS+-Haraka-128f-robust", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusHaraka128frobustKeyPairGeneratorSpi");
        put("KeyPairGenerator.SPHINCS+-Haraka-128f-simple", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusHaraka128fsimpleKeyPairGeneratorSpi");
        put("KeyPairGenerator.SPHINCS+-Haraka-128s-robust", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusHaraka128srobustKeyPairGeneratorSpi");
        put("KeyPairGenerator.SPHINCS+-Haraka-128s-simple", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusHaraka128ssimpleKeyPairGeneratorSpi");
        put("KeyPairGenerator.SPHINCS+-Haraka-192f-robust", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusHaraka192frobustKeyPairGeneratorSpi");
        put("KeyPairGenerator.SPHINCS+-Haraka-192f-simple", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusHaraka192fsimpleKeyPairGeneratorSpi");
        put("KeyPairGenerator.SPHINCS+-Haraka-192s-robust", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusHaraka192srobustKeyPairGeneratorSpi");
        put("KeyPairGenerator.SPHINCS+-Haraka-192s-simple", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusHaraka192ssimpleKeyPairGeneratorSpi");
        put("KeyPairGenerator.SPHINCS+-Haraka-256f-robust", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusHaraka256frobustKeyPairGeneratorSpi");
        put("KeyPairGenerator.SPHINCS+-Haraka-256f-simple", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusHaraka256fsimpleKeyPairGeneratorSpi");
        put("KeyPairGenerator.SPHINCS+-Haraka-256s-robust", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusHaraka256srobustKeyPairGeneratorSpi");
        put("KeyPairGenerator.SPHINCS+-Haraka-256s-simple", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusHaraka256ssimpleKeyPairGeneratorSpi");
        put("KeyPairGenerator.SPHINCS+-SHA256-128f-robust", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHA256128frobustKeyPairGeneratorSpi");
        put("KeyPairGenerator.SPHINCS+-SHA256-128f-simple", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHA256128fsimpleKeyPairGeneratorSpi");
        put("KeyPairGenerator.SPHINCS+-SHA256-128s-robust", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHA256128srobustKeyPairGeneratorSpi");
        put("KeyPairGenerator.SPHINCS+-SHA256-128s-simple", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHA256128ssimpleKeyPairGeneratorSpi");
        put("KeyPairGenerator.SPHINCS+-SHA256-192f-robust", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHA256192frobustKeyPairGeneratorSpi");
        put("KeyPairGenerator.SPHINCS+-SHA256-192f-simple", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHA256192fsimpleKeyPairGeneratorSpi");
        put("KeyPairGenerator.SPHINCS+-SHA256-192s-robust", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHA256192srobustKeyPairGeneratorSpi");
        put("KeyPairGenerator.SPHINCS+-SHA256-192s-simple", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHA256192ssimpleKeyPairGeneratorSpi");
        put("KeyPairGenerator.SPHINCS+-SHA256-256f-robust", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHA256256frobustKeyPairGeneratorSpi");
        put("KeyPairGenerator.SPHINCS+-SHA256-256f-simple", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHA256256fsimpleKeyPairGeneratorSpi");
        put("KeyPairGenerator.SPHINCS+-SHA256-256s-robust", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHA256256srobustKeyPairGeneratorSpi");
        put("KeyPairGenerator.SPHINCS+-SHA256-256s-simple", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHA256256ssimpleKeyPairGeneratorSpi");
        put("KeyPairGenerator.SPHINCS+-SHAKE256-128f-robust", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHAKE256128frobustKeyPairGeneratorSpi");
        put("KeyPairGenerator.SPHINCS+-SHAKE256-128f-simple", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHAKE256128fsimpleKeyPairGeneratorSpi");
        put("KeyPairGenerator.SPHINCS+-SHAKE256-128s-robust", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHAKE256128srobustKeyPairGeneratorSpi");
        put("KeyPairGenerator.SPHINCS+-SHAKE256-128s-simple", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHAKE256128ssimpleKeyPairGeneratorSpi");
        put("KeyPairGenerator.SPHINCS+-SHAKE256-192f-robust", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHAKE256192frobustKeyPairGeneratorSpi");
        put("KeyPairGenerator.SPHINCS+-SHAKE256-192f-simple", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHAKE256192fsimpleKeyPairGeneratorSpi");
        put("KeyPairGenerator.SPHINCS+-SHAKE256-192s-robust", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHAKE256192srobustKeyPairGeneratorSpi");
        put("KeyPairGenerator.SPHINCS+-SHAKE256-192s-simple", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHAKE256192ssimpleKeyPairGeneratorSpi");
        put("KeyPairGenerator.SPHINCS+-SHAKE256-256f-robust", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHAKE256256frobustKeyPairGeneratorSpi");
        put("KeyPairGenerator.SPHINCS+-SHAKE256-256f-simple", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHAKE256256fsimpleKeyPairGeneratorSpi");
        put("KeyPairGenerator.SPHINCS+-SHAKE256-256s-robust", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHAKE256256srobustKeyPairGeneratorSpi");
        put("KeyPairGenerator.SPHINCS+-SHAKE256-256s-simple", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHAKE256256ssimpleKeyPairGeneratorSpi");
        put("KeyPairGenerator.picnic_L1_FS", "com.thatsdarlingmama.security.keypairgenerator.picnicL1FSKeyPairGeneratorSpi");
        put("KeyPairGenerator.picnic_L1_UR", "com.thatsdarlingmama.security.keypairgenerator.picnicL1URKeyPairGeneratorSpi");
        put("KeyPairGenerator.picnic_L1_full", "com.thatsdarlingmama.security.keypairgenerator.picnicL1fullKeyPairGeneratorSpi");
        put("KeyPairGenerator.picnic_L3_FS", "com.thatsdarlingmama.security.keypairgenerator.picnicL3FSKeyPairGeneratorSpi");
        put("KeyPairGenerator.picnic_L3_UR", "com.thatsdarlingmama.security.keypairgenerator.picnicL3URKeyPairGeneratorSpi");
        put("KeyPairGenerator.picnic_L3_full", "com.thatsdarlingmama.security.keypairgenerator.picnicL3fullKeyPairGeneratorSpi");
        put("KeyPairGenerator.picnic_L5_FS", "com.thatsdarlingmama.security.keypairgenerator.picnicL5FSKeyPairGeneratorSpi");
        put("KeyPairGenerator.picnic_L5_UR", "com.thatsdarlingmama.security.keypairgenerator.picnicL5URKeyPairGeneratorSpi");
        put("KeyPairGenerator.picnic_L5_full", "com.thatsdarlingmama.security.keypairgenerator.picnicL5fullKeyPairGeneratorSpi");
        put("KeyPairGenerator.picnic3_L1", "com.thatsdarlingmama.security.keypairgenerator.picnic3L1KeyPairGeneratorSpi");
        put("KeyPairGenerator.picnic3_L3", "com.thatsdarlingmama.security.keypairgenerator.picnic3L3KeyPairGeneratorSpi");
        put("KeyPairGenerator.picnic3_L5", "com.thatsdarlingmama.security.keypairgenerator.picnic3L5KeyPairGeneratorSpi");

        putService(new Service(this,"Signature", "Dilithium2", "com.thatsdarlingmama.security.signature.Dilithium2SignatureSpi", null, null));
        putService(new Service(this,"Signature", "Dilithium3", "com.thatsdarlingmama.security.signature.Dilithium3SignatureSpi", null, null));
        putService(new Service(this,"Signature", "Dilithium5", "com.thatsdarlingmama.security.signature.Dilithium5SignatureSpi", null, null));
        putService(new Service(this,"Signature", "Dilithium2-AES", "com.thatsdarlingmama.security.signature.Dilithium2AESSignatureSpi", null, null));
        putService(new Service(this,"Signature", "Dilithium3-AES", "com.thatsdarlingmama.security.signature.Dilithium3AESSignatureSpi", null, null));
        putService(new Service(this,"Signature", "Dilithium5-AES", "com.thatsdarlingmama.security.signature.Dilithium5AESSignatureSpi", null, null));
        putService(new Service(this,"Signature", "Falcon-512", "com.thatsdarlingmama.security.signature.Falcon512SignatureSpi", null, null));
        putService(new Service(this,"Signature", "Falcon-1024", "com.thatsdarlingmama.security.signature.Falcon1024SignatureSpi", null, null));
        putService(new Service(this,"Signature", "Rainbow-I-Classic", "com.thatsdarlingmama.security.signature.RainbowIClassicSignatureSpi", null, null));
        putService(new Service(this,"Signature", "Rainbow-I-Circumzenithal", "com.thatsdarlingmama.security.signature.RainbowICircumzenithalSignatureSpi", null, null));
        putService(new Service(this,"Signature", "Rainbow-I-Compressed", "com.thatsdarlingmama.security.signature.RainbowICompressedSignatureSpi", null, null));
        putService(new Service(this,"Signature", "Rainbow-III-Classic", "com.thatsdarlingmama.security.signature.RainbowIIIClassicSignatureSpi", null, null));
        putService(new Service(this,"Signature", "Rainbow-III-Circumzenithal", "com.thatsdarlingmama.security.signature.RainbowIIICircumzenithalSignatureSpi", null, null));
        putService(new Service(this,"Signature", "Rainbow-III-Compressed", "com.thatsdarlingmama.security.signature.RainbowIIICompressedSignatureSpi", null, null));
        putService(new Service(this,"Signature", "Rainbow-V-Classic", "com.thatsdarlingmama.security.signature.RainbowVClassicSignatureSpi", null, null));
        putService(new Service(this,"Signature", "Rainbow-V-Circumzenithal", "com.thatsdarlingmama.security.signature.RainbowVCircumzenithalSignatureSpi", null, null));
        putService(new Service(this,"Signature", "Rainbow-V-Compressed", "com.thatsdarlingmama.security.signature.RainbowVCompressedSignatureSpi", null, null));
        putService(new Service(this,"Signature", "SPHINCS+-Haraka-128f-robust", "com.thatsdarlingmama.security.signature.SPHINCSPlusHaraka128frobustSignatureSpi", null, null));
        putService(new Service(this,"Signature", "SPHINCS+-Haraka-128f-simple", "com.thatsdarlingmama.security.signature.SPHINCSPlusHaraka128fsimpleSignatureSpi", null, null));
        putService(new Service(this,"Signature", "SPHINCS+-Haraka-128s-robust", "com.thatsdarlingmama.security.signature.SPHINCSPlusHaraka128srobustSignatureSpi", null, null));
        putService(new Service(this,"Signature", "SPHINCS+-Haraka-128s-simple", "com.thatsdarlingmama.security.signature.SPHINCSPlusHaraka128ssimpleSignatureSpi", null, null));
        putService(new Service(this,"Signature", "SPHINCS+-Haraka-192f-robust", "com.thatsdarlingmama.security.signature.SPHINCSPlusHaraka192frobustSignatureSpi", null, null));
        putService(new Service(this,"Signature", "SPHINCS+-Haraka-192f-simple", "com.thatsdarlingmama.security.signature.SPHINCSPlusHaraka192fsimpleSignatureSpi", null, null));
        putService(new Service(this,"Signature", "SPHINCS+-Haraka-192s-robust", "com.thatsdarlingmama.security.signature.SPHINCSPlusHaraka192srobustSignatureSpi", null, null));
        putService(new Service(this,"Signature", "SPHINCS+-Haraka-192s-simple", "com.thatsdarlingmama.security.signature.SPHINCSPlusHaraka192ssimpleSignatureSpi", null, null));
        putService(new Service(this,"Signature", "SPHINCS+-Haraka-256f-robust", "com.thatsdarlingmama.security.signature.SPHINCSPlusHaraka256frobustSignatureSpi", null, null));
        putService(new Service(this,"Signature", "SPHINCS+-Haraka-256f-simple", "com.thatsdarlingmama.security.signature.SPHINCSPlusHaraka256fsimpleSignatureSpi", null, null));
        putService(new Service(this,"Signature", "SPHINCS+-Haraka-256s-robust", "com.thatsdarlingmama.security.signature.SPHINCSPlusHaraka256srobustSignatureSpi", null, null));
        putService(new Service(this,"Signature", "SPHINCS+-Haraka-256s-simple", "com.thatsdarlingmama.security.signature.SPHINCSPlusHaraka256ssimpleSignatureSpi", null, null));
        putService(new Service(this,"Signature", "SPHINCS+-SHA256-128f-robust", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHA256128frobustSignatureSpi", null, null));
        putService(new Service(this,"Signature", "SPHINCS+-SHA256-128f-simple", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHA256128fsimpleSignatureSpi", null, null));
        putService(new Service(this,"Signature", "SPHINCS+-SHA256-128s-robust", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHA256128srobustSignatureSpi", null, null));
        putService(new Service(this,"Signature", "SPHINCS+-SHA256-128s-simple", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHA256128ssimpleSignatureSpi", null, null));
        putService(new Service(this,"Signature", "SPHINCS+-SHA256-192f-robust", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHA256192frobustSignatureSpi", null, null));
        putService(new Service(this,"Signature", "SPHINCS+-SHA256-192f-simple", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHA256192fsimpleSignatureSpi", null, null));
        putService(new Service(this,"Signature", "SPHINCS+-SHA256-192s-robust", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHA256192srobustSignatureSpi", null, null));
        putService(new Service(this,"Signature", "SPHINCS+-SHA256-192s-simple", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHA256192ssimpleSignatureSpi", null, null));
        putService(new Service(this,"Signature", "SPHINCS+-SHA256-256f-robust", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHA256256frobustSignatureSpi", null, null));
        putService(new Service(this,"Signature", "SPHINCS+-SHA256-256f-simple", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHA256256fsimpleSignatureSpi", null, null));
        putService(new Service(this,"Signature", "SPHINCS+-SHA256-256s-robust", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHA256256srobustSignatureSpi", null, null));
        putService(new Service(this,"Signature", "SPHINCS+-SHA256-256s-simple", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHA256256ssimpleSignatureSpi", null, null));
        putService(new Service(this,"Signature", "SPHINCS+-SHAKE256-128f-robust", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHAKE256128frobustSignatureSpi", null, null));
        putService(new Service(this,"Signature", "SPHINCS+-SHAKE256-128f-simple", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHAKE256128fsimpleSignatureSpi", null, null));
        putService(new Service(this,"Signature", "SPHINCS+-SHAKE256-128s-robust", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHAKE256128srobustSignatureSpi", null, null));
        putService(new Service(this,"Signature", "SPHINCS+-SHAKE256-128s-simple", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHAKE256128ssimpleSignatureSpi", null, null));
        putService(new Service(this,"Signature", "SPHINCS+-SHAKE256-192f-robust", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHAKE256192frobustSignatureSpi", null, null));
        putService(new Service(this,"Signature", "SPHINCS+-SHAKE256-192f-simple", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHAKE256192fsimpleSignatureSpi", null, null));
        putService(new Service(this,"Signature", "SPHINCS+-SHAKE256-192s-robust", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHAKE256192srobustSignatureSpi", null, null));
        putService(new Service(this,"Signature", "SPHINCS+-SHAKE256-192s-simple", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHAKE256192ssimpleSignatureSpi", null, null));
        putService(new Service(this,"Signature", "SPHINCS+-SHAKE256-256f-robust", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHAKE256256frobustSignatureSpi", null, null));
        putService(new Service(this,"Signature", "SPHINCS+-SHAKE256-256f-simple", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHAKE256256fsimpleSignatureSpi", null, null));
        putService(new Service(this,"Signature", "SPHINCS+-SHAKE256-256s-robust", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHAKE256256srobustSignatureSpi", null, null));
        putService(new Service(this,"Signature", "SPHINCS+-SHAKE256-256s-simple", "com.thatsdarlingmama.security.signature.SPHINCSPlusSHAKE256256ssimpleSignatureSpi", null, null));
        putService(new Service(this,"Signature", "picnic_L1_FS", "com.thatsdarlingmama.security.signature.picnicL1FSSignatureSpi", null, null));
        putService(new Service(this,"Signature", "picnic_L1_UR", "com.thatsdarlingmama.security.signature.picnicL1URSignatureSpi", null, null));
        putService(new Service(this,"Signature", "picnic_L1_full", "com.thatsdarlingmama.security.signature.picnicL1fullSignatureSpi", null, null));
        putService(new Service(this,"Signature", "picnic_L3_FS", "com.thatsdarlingmama.security.signature.picnicL3FSSignatureSpi", null, null));
        putService(new Service(this,"Signature", "picnic_L3_UR", "com.thatsdarlingmama.security.signature.picnicL3URSignatureSpi", null, null));
        putService(new Service(this,"Signature", "picnic_L3_full", "com.thatsdarlingmama.security.signature.picnicL3fullSignatureSpi", null, null));
        putService(new Service(this,"Signature", "picnic_L5_FS", "com.thatsdarlingmama.security.signature.picnicL5FSSignatureSpi", null, null));
        putService(new Service(this,"Signature", "picnic_L5_UR", "com.thatsdarlingmama.security.signature.picnicL5URSignatureSpi", null, null));
        putService(new Service(this,"Signature", "picnic_L5_full", "com.thatsdarlingmama.security.signature.picnicL5fullSignatureSpi", null, null));
        putService(new Service(this,"Signature", "picnic3_L1", "com.thatsdarlingmama.security.signature.picnic3L1SignatureSpi", null, null));
        putService(new Service(this,"Signature", "picnic3_L3", "com.thatsdarlingmama.security.signature.picnic3L3SignatureSpi", null, null));
        putService(new Service(this,"Signature", "picnic3_L5", "com.thatsdarlingmama.security.signature.picnic3L5SignatureSpi", null, null));

        putService(new Service(this,"KeyAgreement", "LightSaber-KEM", "com.thatsdarlingmama.security.keyagreement.LightSaberKEMKeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "BIKE-L1", "com.thatsdarlingmama.security.keyagreement.BIKEL1KeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "BIKE-L3", "com.thatsdarlingmama.security.keyagreement.BIKEL3KeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "Classic-McEliece-348864", "com.thatsdarlingmama.security.keyagreement.ClassicMcEliece348864KeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "Classic-McEliece-348864f", "com.thatsdarlingmama.security.keyagreement.ClassicMcEliece348864fKeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "Classic-McEliece-460896", "com.thatsdarlingmama.security.keyagreement.ClassicMcEliece460896KeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "Classic-McEliece-460896f", "com.thatsdarlingmama.security.keyagreement.ClassicMcEliece460896fKeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "Classic-McEliece-6688128", "com.thatsdarlingmama.security.keyagreement.ClassicMcEliece6688128KeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "Classic-McEliece-6688128f", "com.thatsdarlingmama.security.keyagreement.ClassicMcEliece6688128fKeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "Classic-McEliece-6960119", "com.thatsdarlingmama.security.keyagreement.ClassicMcEliece6960119KeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "Classic-McEliece-6960119f", "com.thatsdarlingmama.security.keyagreement.ClassicMcEliece6960119fKeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "Classic-McEliece-8192128", "com.thatsdarlingmama.security.keyagreement.ClassicMcEliece8192128KeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "Classic-McEliece-8192128f", "com.thatsdarlingmama.security.keyagreement.ClassicMcEliece8192128fKeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "HQC-128", "com.thatsdarlingmama.security.keyagreement.HQC128KeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "HQC-192", "com.thatsdarlingmama.security.keyagreement.HQC192KeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "HQC-256", "com.thatsdarlingmama.security.keyagreement.HQC256KeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "Kyber512", "com.thatsdarlingmama.security.keyagreement.Kyber512KeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "Kyber768", "com.thatsdarlingmama.security.keyagreement.Kyber768KeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "Kyber1024", "com.thatsdarlingmama.security.keyagreement.Kyber1024KeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "Kyber512-90s", "com.thatsdarlingmama.security.keyagreement.Kyber51290sKeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "Kyber768-90s", "com.thatsdarlingmama.security.keyagreement.Kyber76890sKeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "Kyber1024-90s", "com.thatsdarlingmama.security.keyagreement.Kyber102490sKeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "NTRU-HPS-2048-509", "com.thatsdarlingmama.security.keyagreement.NTRUHPS2048509KeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "NTRU-HPS-2048-677", "com.thatsdarlingmama.security.keyagreement.NTRUHPS2048677KeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "NTRU-HPS-4096-821", "com.thatsdarlingmama.security.keyagreement.NTRUHPS4096821KeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "NTRU-HPS-4096-1229", "com.thatsdarlingmama.security.keyagreement.NTRUHPS40961229KeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "NTRU-HRSS-701", "com.thatsdarlingmama.security.keyagreement.NTRUHRSS701KeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "NTRU-HRSS-1373", "com.thatsdarlingmama.security.keyagreement.NTRUHRSS1373KeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "ntrulpr653", "com.thatsdarlingmama.security.keyagreement.ntrulpr653KeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "ntrulpr761", "com.thatsdarlingmama.security.keyagreement.ntrulpr761KeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "ntrulpr857", "com.thatsdarlingmama.security.keyagreement.ntrulpr857KeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "ntrulpr1277", "com.thatsdarlingmama.security.keyagreement.ntrulpr1277KeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "sntrup653", "com.thatsdarlingmama.security.keyagreement.sntrup653KeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "sntrup761", "com.thatsdarlingmama.security.keyagreement.sntrup761KeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "sntrup857", "com.thatsdarlingmama.security.keyagreement.sntrup857KeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "sntrup1277", "com.thatsdarlingmama.security.keyagreement.sntrup1277KeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "LightSaber-KEM", "com.thatsdarlingmama.security.keyagreement.LightSaberKEMKeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "Saber-KEM", "com.thatsdarlingmama.security.keyagreement.SaberKEMKeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "FireSaber-KEM", "com.thatsdarlingmama.security.keyagreement.FireSaberKEMKeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "FrodoKEM-640-AES", "com.thatsdarlingmama.security.keyagreement.FrodoKEM640AESKeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "FrodoKEM-640-SHAKE", "com.thatsdarlingmama.security.keyagreement.FrodoKEM640SHAKEKeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "FrodoKEM-976-AES", "com.thatsdarlingmama.security.keyagreement.FrodoKEM976AESKeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "FrodoKEM-976-SHAKE", "com.thatsdarlingmama.security.keyagreement.FrodoKEM976SHAKEKeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "FrodoKEM-1344-AES", "com.thatsdarlingmama.security.keyagreement.FrodoKEM1344AESKeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "FrodoKEM-1344-SHAKE", "com.thatsdarlingmama.security.keyagreement.FrodoKEM1344SHAKEKeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "SIDH-p434", "com.thatsdarlingmama.security.keyagreement.SIDHp434KeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "SIDH-p503", "com.thatsdarlingmama.security.keyagreement.SIDHp503KeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "SIDH-p610", "com.thatsdarlingmama.security.keyagreement.SIDHp610KeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "SIDH-p751", "com.thatsdarlingmama.security.keyagreement.SIDHp751KeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "SIDH-p434-compressed", "com.thatsdarlingmama.security.keyagreement.SIDHp434compressedKeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "SIDH-p503-compressed", "com.thatsdarlingmama.security.keyagreement.SIDHp503compressedKeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "SIDH-p610-compressed", "com.thatsdarlingmama.security.keyagreement.SIDHp610compressedKeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "SIDH-p751-compressed", "com.thatsdarlingmama.security.keyagreement.SIDHp751compressedKeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "SIKE-p434", "com.thatsdarlingmama.security.keyagreement.SIKEp434KeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "SIKE-p503", "com.thatsdarlingmama.security.keyagreement.SIKEp503KeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "SIKE-p610", "com.thatsdarlingmama.security.keyagreement.SIKEp610KeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "SIKE-p751", "com.thatsdarlingmama.security.keyagreement.SIKEp751KeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "SIKE-p434-compressed", "com.thatsdarlingmama.security.keyagreement.SIKEp434compressedKeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "SIKE-p503-compressed", "com.thatsdarlingmama.security.keyagreement.SIKEp503compressedKeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "SIKE-p610-compressed", "com.thatsdarlingmama.security.keyagreement.SIKEp610compressedKeyAgreementSpi", null, null));
        putService(new Service(this,"KeyAgreement", "SIKE-p751-compressed", "com.thatsdarlingmama.security.keyagreement.SIKEp751compressedKeyAgreementSpi", null, null));

        putService(new Service(this, "KeyPairGenerator", "BIKE-L1", "com.thatsdarlingmama.security.keypairgenerator.BIKEL1KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "BIKE-L3", "com.thatsdarlingmama.security.keypairgenerator.BIKEL3KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "Classic-McEliece-348864", "com.thatsdarlingmama.security.keypairgenerator.ClassicMcEliece348864KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "Classic-McEliece-348864f", "com.thatsdarlingmama.security.keypairgenerator.ClassicMcEliece348864fKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "Classic-McEliece-460896", "com.thatsdarlingmama.security.keypairgenerator.ClassicMcEliece460896KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "Classic-McEliece-460896f", "com.thatsdarlingmama.security.keypairgenerator.ClassicMcEliece460896fKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "Classic-McEliece-6688128", "com.thatsdarlingmama.security.keypairgenerator.ClassicMcEliece6688128KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "Classic-McEliece-6688128f", "com.thatsdarlingmama.security.keypairgenerator.ClassicMcEliece6688128fKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "Classic-McEliece-6960119", "com.thatsdarlingmama.security.keypairgenerator.ClassicMcEliece6960119KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "Classic-McEliece-6960119f", "com.thatsdarlingmama.security.keypairgenerator.ClassicMcEliece6960119fKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "Classic-McEliece-8192128", "com.thatsdarlingmama.security.keypairgenerator.ClassicMcEliece8192128KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "Classic-McEliece-8192128f", "com.thatsdarlingmama.security.keypairgenerator.ClassicMcEliece8192128fKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "HQC-128", "com.thatsdarlingmama.security.keypairgenerator.HQC128KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "HQC-192", "com.thatsdarlingmama.security.keypairgenerator.HQC192KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "HQC-256", "com.thatsdarlingmama.security.keypairgenerator.HQC256KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "Kyber512", "com.thatsdarlingmama.security.keypairgenerator.Kyber512KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "Kyber768", "com.thatsdarlingmama.security.keypairgenerator.Kyber768KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "Kyber1024", "com.thatsdarlingmama.security.keypairgenerator.Kyber1024KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "Kyber512-90s", "com.thatsdarlingmama.security.keypairgenerator.Kyber51290sKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "Kyber768-90s", "com.thatsdarlingmama.security.keypairgenerator.Kyber76890sKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "Kyber1024-90s", "com.thatsdarlingmama.security.keypairgenerator.Kyber102490sKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "NTRU-HPS-2048-509", "com.thatsdarlingmama.security.keypairgenerator.NTRUHPS2048509KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "NTRU-HPS-2048-677", "com.thatsdarlingmama.security.keypairgenerator.NTRUHPS2048677KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "NTRU-HPS-4096-821", "com.thatsdarlingmama.security.keypairgenerator.NTRUHPS4096821KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "NTRU-HPS-4096-1229", "com.thatsdarlingmama.security.keypairgenerator.NTRUHPS40961229KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "NTRU-HRSS-701", "com.thatsdarlingmama.security.keypairgenerator.NTRUHRSS701KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "NTRU-HRSS-1373", "com.thatsdarlingmama.security.keypairgenerator.NTRUHRSS1373KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "ntrulpr653", "com.thatsdarlingmama.security.keypairgenerator.ntrulpr653KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "ntrulpr761", "com.thatsdarlingmama.security.keypairgenerator.ntrulpr761KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "ntrulpr857", "com.thatsdarlingmama.security.keypairgenerator.ntrulpr857KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "ntrulpr1277", "com.thatsdarlingmama.security.keypairgenerator.ntrulpr1277KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "sntrup653", "com.thatsdarlingmama.security.keypairgenerator.sntrup653KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "sntrup761", "com.thatsdarlingmama.security.keypairgenerator.sntrup761KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "sntrup857", "com.thatsdarlingmama.security.keypairgenerator.sntrup857KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "sntrup1277", "com.thatsdarlingmama.security.keypairgenerator.sntrup1277KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "LightSaber-KEM", "com.thatsdarlingmama.security.keypairgenerator.LightSaberKEMKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "Saber-KEM", "com.thatsdarlingmama.security.keypairgenerator.SaberKEMKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "FireSaber-KEM", "com.thatsdarlingmama.security.keypairgenerator.FireSaberKEMKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "FrodoKEM-640-AES", "com.thatsdarlingmama.security.keypairgenerator.FrodoKEM640AESKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "FrodoKEM-640-SHAKE", "com.thatsdarlingmama.security.keypairgenerator.FrodoKEM640SHAKEKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "FrodoKEM-976-AES", "com.thatsdarlingmama.security.keypairgenerator.FrodoKEM976AESKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "FrodoKEM-976-SHAKE", "com.thatsdarlingmama.security.keypairgenerator.FrodoKEM976SHAKEKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "FrodoKEM-1344-AES", "com.thatsdarlingmama.security.keypairgenerator.FrodoKEM1344AESKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "FrodoKEM-1344-SHAKE", "com.thatsdarlingmama.security.keypairgenerator.FrodoKEM1344SHAKEKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SIDH-p434", "com.thatsdarlingmama.security.keypairgenerator.SIDHp434KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SIDH-p503", "com.thatsdarlingmama.security.keypairgenerator.SIDHp503KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SIDH-p610", "com.thatsdarlingmama.security.keypairgenerator.SIDHp610KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SIDH-p751", "com.thatsdarlingmama.security.keypairgenerator.SIDHp751KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SIDH-p434-compressed", "com.thatsdarlingmama.security.keypairgenerator.SIDHp434compressedKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SIDH-p503-compressed", "com.thatsdarlingmama.security.keypairgenerator.SIDHp503compressedKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SIDH-p610-compressed", "com.thatsdarlingmama.security.keypairgenerator.SIDHp610compressedKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SIDH-p751-compressed", "com.thatsdarlingmama.security.keypairgenerator.SIDHp751compressedKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SIKE-p434", "com.thatsdarlingmama.security.keypairgenerator.SIKEp434KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SIKE-p503", "com.thatsdarlingmama.security.keypairgenerator.SIKEp503KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SIKE-p610", "com.thatsdarlingmama.security.keypairgenerator.SIKEp610KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SIKE-p751", "com.thatsdarlingmama.security.keypairgenerator.SIKEp751KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SIKE-p434-compressed", "com.thatsdarlingmama.security.keypairgenerator.SIKEp434compressedKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SIKE-p503-compressed", "com.thatsdarlingmama.security.keypairgenerator.SIKEp503compressedKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SIKE-p610-compressed", "com.thatsdarlingmama.security.keypairgenerator.SIKEp610compressedKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SIKE-p751-compressed", "com.thatsdarlingmama.security.keypairgenerator.SIKEp751compressedKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "Dilithium2", "com.thatsdarlingmama.security.keypairgenerator.Dilithium2KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "Dilithium3", "com.thatsdarlingmama.security.keypairgenerator.Dilithium3KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "Dilithium5", "com.thatsdarlingmama.security.keypairgenerator.Dilithium5KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "Dilithium2-AES", "com.thatsdarlingmama.security.keypairgenerator.Dilithium2AESKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "Dilithium3-AES", "com.thatsdarlingmama.security.keypairgenerator.Dilithium3AESKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "Dilithium5-AES", "com.thatsdarlingmama.security.keypairgenerator.Dilithium5AESKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "Falcon-512", "com.thatsdarlingmama.security.keypairgenerator.Falcon512KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "Falcon-1024", "com.thatsdarlingmama.security.keypairgenerator.Falcon1024KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "Rainbow-I-Classic", "com.thatsdarlingmama.security.keypairgenerator.RainbowIClassicKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "Rainbow-I-Circumzenithal", "com.thatsdarlingmama.security.keypairgenerator.RainbowICircumzenithalKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "Rainbow-I-Compressed", "com.thatsdarlingmama.security.keypairgenerator.RainbowICompressedKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "Rainbow-III-Classic", "com.thatsdarlingmama.security.keypairgenerator.RainbowIIIClassicKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "Rainbow-III-Circumzenithal", "com.thatsdarlingmama.security.keypairgenerator.RainbowIIICircumzenithalKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "Rainbow-III-Compressed", "com.thatsdarlingmama.security.keypairgenerator.RainbowIIICompressedKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "Rainbow-V-Classic", "com.thatsdarlingmama.security.keypairgenerator.RainbowVClassicKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "Rainbow-V-Circumzenithal", "com.thatsdarlingmama.security.keypairgenerator.RainbowVCircumzenithalKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "Rainbow-V-Compressed", "com.thatsdarlingmama.security.keypairgenerator.RainbowVCompressedKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SPHINCS+-Haraka-128f-robust", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusHaraka128frobustKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SPHINCS+-Haraka-128f-simple", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusHaraka128fsimpleKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SPHINCS+-Haraka-128s-robust", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusHaraka128srobustKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SPHINCS+-Haraka-128s-simple", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusHaraka128ssimpleKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SPHINCS+-Haraka-192f-robust", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusHaraka192frobustKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SPHINCS+-Haraka-192f-simple", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusHaraka192fsimpleKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SPHINCS+-Haraka-192s-robust", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusHaraka192srobustKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SPHINCS+-Haraka-192s-simple", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusHaraka192ssimpleKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SPHINCS+-Haraka-256f-robust", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusHaraka256frobustKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SPHINCS+-Haraka-256f-simple", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusHaraka256fsimpleKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SPHINCS+-Haraka-256s-robust", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusHaraka256srobustKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SPHINCS+-Haraka-256s-simple", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusHaraka256ssimpleKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SPHINCS+-SHA256-128f-robust", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHA256128frobustKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SPHINCS+-SHA256-128f-simple", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHA256128fsimpleKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SPHINCS+-SHA256-128s-robust", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHA256128srobustKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SPHINCS+-SHA256-128s-simple", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHA256128ssimpleKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SPHINCS+-SHA256-192f-robust", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHA256192frobustKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SPHINCS+-SHA256-192f-simple", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHA256192fsimpleKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SPHINCS+-SHA256-192s-robust", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHA256192srobustKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SPHINCS+-SHA256-192s-simple", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHA256192ssimpleKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SPHINCS+-SHA256-256f-robust", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHA256256frobustKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SPHINCS+-SHA256-256f-simple", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHA256256fsimpleKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SPHINCS+-SHA256-256s-robust", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHA256256srobustKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SPHINCS+-SHA256-256s-simple", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHA256256ssimpleKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SPHINCS+-SHAKE256-128f-robust", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHAKE256128frobustKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SPHINCS+-SHAKE256-128f-simple", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHAKE256128fsimpleKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SPHINCS+-SHAKE256-128s-robust", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHAKE256128srobustKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SPHINCS+-SHAKE256-128s-simple", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHAKE256128ssimpleKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SPHINCS+-SHAKE256-192f-robust", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHAKE256192frobustKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SPHINCS+-SHAKE256-192f-simple", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHAKE256192fsimpleKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SPHINCS+-SHAKE256-192s-robust", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHAKE256192srobustKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SPHINCS+-SHAKE256-192s-simple", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHAKE256192ssimpleKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SPHINCS+-SHAKE256-256f-robust", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHAKE256256frobustKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SPHINCS+-SHAKE256-256f-simple", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHAKE256256fsimpleKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SPHINCS+-SHAKE256-256s-robust", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHAKE256256srobustKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "SPHINCS+-SHAKE256-256s-simple", "com.thatsdarlingmama.security.keypairgenerator.SPHINCSPlusSHAKE256256ssimpleKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "picnic_L1_FS", "com.thatsdarlingmama.security.keypairgenerator.picnicL1FSKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "picnic_L1_UR", "com.thatsdarlingmama.security.keypairgenerator.picnicL1URKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "picnic_L1_full", "com.thatsdarlingmama.security.keypairgenerator.picnicL1fullKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "picnic_L3_FS", "com.thatsdarlingmama.security.keypairgenerator.picnicL3FSKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "picnic_L3_UR", "com.thatsdarlingmama.security.keypairgenerator.picnicL3URKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "picnic_L3_full", "com.thatsdarlingmama.security.keypairgenerator.picnicL3fullKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "picnic_L5_FS", "com.thatsdarlingmama.security.keypairgenerator.picnicL5FSKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "picnic_L5_UR", "com.thatsdarlingmama.security.keypairgenerator.picnicL5URKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "picnic_L5_full", "com.thatsdarlingmama.security.keypairgenerator.picnicL5fullKeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "picnic3_L1", "com.thatsdarlingmama.security.keypairgenerator.picnic3L1KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "picnic3_L3", "com.thatsdarlingmama.security.keypairgenerator.picnic3L3KeyPairGeneratorSpi", null, null));
        putService(new Service(this, "KeyPairGenerator", "picnic3_L5", "com.thatsdarlingmama.security.keypairgenerator.picnic3L5KeyPairGeneratorSpi", null, null));
    }
}
