/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thatsdarlingmama_nat_LeanCryptoNative */

#ifndef _Included_com_thatsdarlingmama_nat_LeanCryptoNative
#define _Included_com_thatsdarlingmama_nat_LeanCryptoNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_thatsdarlingmama_nat_LeanCryptoNative
 * Method:    GetKeyPair
 * Signature: (Ljava/lang/String;)Ljava/security/KeyPair;
 */
JNIEXPORT jobject JNICALL Java_com_thatsdarlingmama_nat_LeanCryptoNative_GetKeyPair
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
