/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LeanCryptoNative */

#ifndef _Included_LeanCryptoNative
#define _Included_LeanCryptoNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LeanCryptoNative
 * Method:    GetKeyPair
 * Signature: (Ljava/lang/String;)Ljava/security/KeyPair;
 */
JNIEXPORT jobject JNICALL Java_LeanCryptoNative_GetKeyPair
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
